In [1]:
import numpy as np

In [4]:
data=np.random.randn(4,3,2)

In [5]:
data

array([[[ 1.43577055, -1.09567592],
        [-1.16024223,  1.69514893],
        [-0.79425878, -0.12577742]],

       [[ 0.57035865, -0.93910089],
        [ 1.42804669, -0.96991087],
        [-0.12818454,  0.45293848]],

       [[ 0.97058687,  1.19806095],
        [ 0.68572952, -0.51077952],
        [ 1.26702196,  0.82900026]],

       [[ 2.3185931 , -0.51298239],
        [ 1.33102782,  0.29294694],
        [-1.40169247,  0.82974203]]])

In [8]:
data[0,1,0]

-1.160242226236032

In [11]:
data2=np.array([1:101])

SyntaxError: invalid syntax (<ipython-input-11-009ba7f124b8>, line 1)

In [12]:
data3=[]

In [17]:
for i in range(0,100):
    data3.append(i)
data2=np.array(range(0,100))

data2

In [18]:
data2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [29]:
dd=np.arange(99,1,-2)

In [30]:
data4=[[1,2,3,4],[5,6,7,8]]

In [31]:
arr=np.array(data4)

In [32]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr.ndim

2

In [34]:
arr.dtype

dtype('int32')

In [35]:
dd.ndim

1

In [36]:
dd.astype('float64')

array([99., 97., 95., 93., 91., 89., 87., 85., 83., 81., 79., 77., 75.,
       73., 71., 69., 67., 65., 63., 61., 59., 57., 55., 53., 51., 49.,
       47., 45., 43., 41., 39., 37., 35., 33., 31., 29., 27., 25., 23.,
       21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.])

In [37]:
dd.astype('string')

TypeError: data type "string" not understood

In [38]:
dd.astype('char64')

TypeError: data type "char64" not understood

In [49]:
zero=np.zeros((2,2),dtype='int64')

In [50]:
zero

array([[0, 0],
       [0, 0]], dtype=int64)

In [54]:
d=np.ones((5,5),dtype='int64')

In [55]:
d=d*5

In [56]:
d

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int64)

In [57]:
d[1:2,2:4]

array([[5, 5]], dtype=int64)

In [59]:
d2=np.zeros((5,5),dtype='int64')
d2[1:4,1:4]=1

In [61]:
d2

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [62]:
d5=np.zeros((5,5),dtype='int64')


In [64]:
d5[2:-1,2:-1]=1

In [65]:
d5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [69]:
d6=np.empty((5,2))

In [70]:
d6

array([[1.14587773e-312, 2.33419537e-312],
       [9.76118064e-313, 2.31297541e-312],
       [2.46151512e-312, 8.48798317e-313],
       [1.12465777e-312, 1.12465777e-312],
       [8.70018274e-313, 0.00000000e+000]])

In [71]:
d6.astype('string_')

array([[b'1.145877727615e-312', b'2.334195370363e-312'],
       [b'9.76118064397e-313', b'2.31297541265e-312'],
       [b'2.461515118073e-312', b'8.48798316984e-313'],
       [b'1.12465776941e-312', b'1.12465776943e-312'],
       [b'8.700182745e-313', b'0.0']], dtype='|S32')

In [76]:
list1=[1,2,3,4,5,6]
list1[1]=0